(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.Contacts=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const statuses=['활성','퇴사·변경','보류'];
const fields=[['company','업체명'],['person','담당자명'],['person_en','영문 이름'],['title','직함'],['duty','담당 업무'],['department','부서'],['country','국가'],['mobile','휴대전화'],['phone','전화'],['fax','팩스'],['email','이메일'],['messenger','메신저'],['website','웹사이트'],['address','주소'],['tags','태그'],['note','메모'],['status','상태'],['customer_id','기존 거래처 연결']];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key=v=>String(v??'').trim().toLowerCase();
function normalize(raw){
 const out={};for(const [name,label]of fields){const value=String(raw[name]??'').trim();if(value.length>(name==='email'?254:4000))throw Error(label+'이 너무 깁니다.');out[name]=value;}
 out.customer_id=out.customer_id||null;if(out.customer_id&&!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(out.customer_id))throw Error('거래처를 목록에서 선택하세요.');
 out.status=out.status||'활성';if(!statuses.includes(out.status))throw Error('상태를 다시 선택하세요.');
 if(!out.company||!out.person)throw Error('업체명과 담당자명을 입력하세요.');
 if(!['mobile','phone','email','messenger'].some(f=>out[f]))throw Error('연락수단을 한 가지 이상 입력하세요.');
 if(out.email&&!/^[^\s@]+@[^\s@.]+(?:\.[^\s@.]+)+$/.test(out.email))throw Error('이메일 형식을 확인하세요.');return out;
}
function isDuplicate(a,b){return !!(key(a.email)&&key(a.email)===key(b.email))||!!(key(a.company)&&key(a.person)&&key(a.company)===key(b.company)&&key(a.person)===key(b.person));}
function filterRows(rows,filter={}){return rows.filter(r=>(!filter.company||r.company===filter.company)&&(!filter.status||r.status===filter.status)&&(!filter.q||fields.map(([f])=>r[f]??'').join(' ').toLowerCase().includes(filter.q.toLowerCase())));}
function renderList({rows=[],pending=[],filter={}}){
 const visible=filterRows(rows,filter),waiting=filterRows(pending,filter),groups=new Map();for(const row of visible){if(!groups.has(row.company))groups.set(row.company,[]);groups.get(row.company).push(row);}
 const card=(r,isPending=false)=>`<article class="contact-card"><header><strong>${esc(r.person)}</strong><span class="badge ${isPending?'bg-amber':'bg-gray'}">${isPending?'승인 대기':esc(r.status)}</span>${!isPending?`<button class="btn btn-sm" data-contact-edit="${esc(r.id)}">상세 / 수정</button>`:''}</header><p>${[r.person_en,r.title,r.department,r.duty,r.country].filter(Boolean).map(esc).join(' · ')}</p><dl>${['mobile','phone','email','messenger'].filter(f=>r[f]).map(f=>`<div><dt>${fields.find(([k])=>k===f)[1]}</dt><dd>${esc(r[f])}</dd></div>`).join('')}</dl>${r.tags?`<small>${esc(r.tags)}</small>`:''}${isPending?`<small>${esc(r.company)} · 요청 접수 완료, 승인 후 반영</small>`:''}</article>`;
 return `<p class="contacts-caption">확정 연락처 ${rows.length}명 · 승인 대기 ${pending.length}건 · 검색 결과 ${visible.length}명</p>${waiting.length?`<section class="contacts-pending"><h3>승인 대기 · 접수 완료</h3><div class="contacts-grid">${waiting.map(r=>card(r,true)).join('')}</div></section>`:''}${[...groups].sort(([a],[b])=>a.localeCompare(b,'ko')).map(([company,list])=>`<section class="contacts-company"><h3>${esc(company)} <small>${list.length}명</small></h3><div class="contacts-grid">${list.map(r=>card(r)).join('')}</div></section>`).join('')||'<p class="contacts-empty">확정 연락처가 없거나 검색 결과가 없습니다.</p>'}`;
}
function createController({read,readPending=async()=>[],submit,onChange=()=>{}}){
 const state={rows:[],pending:[],loading:false,saving:false,error:'',message:''};let epoch=0,generation=0,cancelled=false,local=[];
 const notify=()=>onChange(state),duplicateRows=()=>[...state.rows,...state.pending];
 function mergePending(response){const rows=Array.isArray(response)?response:response.rows,resolved=new Set(response.resolvedIds||[]);if(!Array.isArray(rows))throw Error('승인 대기 목록 응답을 확인할 수 없습니다.');local=local.filter(r=>!resolved.has(r._requestId));state.pending=[...rows,...local.filter(r=>!rows.some(p=>p._requestId&&p._requestId===r._requestId&&isDuplicate(p,r)))];}
 async function refresh(ticket){const [rows,pending]=await Promise.all([read(),readPending()]);if(ticket!==epoch)return false;if(!Array.isArray(rows))throw Error('연락처 목록 응답을 확인할 수 없습니다.');state.rows=rows;mergePending(pending);return true;}
 async function load(){if(state.saving)return false;const ticket=epoch,gen=++generation;state.loading=true;state.error='';notify();try{const [rows,pending]=await Promise.all([read(),readPending()]);if(ticket!==epoch||gen!==generation)return false;if(!Array.isArray(rows))throw Error('연락처 목록 응답을 확인할 수 없습니다.');state.rows=rows;mergePending(pending);return true;}catch(e){if(ticket===epoch&&gen===generation)state.error='연락처 조회 실패: '+e.message;return false;}finally{if(ticket===epoch&&gen===generation){state.loading=false;notify();}}}
 function accept(result,entries){if(!result?.id||!['pending','approved'].includes(result.status))throw Error(result?.status==='rejected'?'반려된 요청입니다. 변경 요청 목록을 확인하세요.':'접수 여부를 확인하지 못했습니다. 변경 요청 목록을 확인하세요.');for(const entry of result.status==='pending'?entries:[]){const pending={...entry.values,id:entry.before?.id,_pending:true,_requestId:result.id,_action:entry.before?'update':'insert'};local.push(pending);state.pending.push(pending);}state.message=result.status==='approved'?'이미 승인된 요청입니다. 새로고침해 확정 연락처를 확인하세요.':'요청이 접수됐습니다. 관리자 승인 후 반영됩니다.';}
 function prepare(raw,before){const values=normalize(raw);if(state.pending.some(r=>(before?.id&&r.id===before.id)||isDuplicate(values,r)))throw Error('이미 승인 대기 중인 연락처입니다.');if(state.rows.some(r=>r.id!==before?.id&&isDuplicate(values,r)))throw Error('기존 연락처와 중복됩니다. 업체·담당자 또는 이메일을 확인하세요.');return{raw,values,before,operation:{table:'contacts',action:before?'update':'insert',key:before?{id:before.id}:{},before:before?JSON.parse(JSON.stringify(before)):null,values}};}
 async function save(raw,before=null,reason=''){
  if(state.saving)return null;const ticket=epoch;state.saving=true;state.error='';state.message='';generation++;state.loading=false;notify();
  try{if(!String(reason).trim())throw Error('등록·수정 사유를 입력하세요.');if(!await refresh(ticket))return null;const entry=prepare(raw,before);const result=await submit([entry.operation],{reason});if(ticket!==epoch)return null;accept(result,[entry]);return result;}catch(e){if(ticket===epoch)state.error=e.message;return null;}finally{if(ticket===epoch){state.saving=false;notify();}}
 }
 async function saveMany(rows,{reason='',onProgress=()=>{}}={}){
  if(state.saving)return{done:[],failed:rows.map(row=>({row,error:'다른 요청을 처리 중입니다.'})),cancelled:false};
  const ticket=epoch,out={done:[],failed:[],cancelled:false};state.saving=true;state.error='';state.message='';cancelled=false;generation++;state.loading=false;notify();
  try{
   if(!String(reason).trim())throw Error('등록 사유를 입력하세요.');if(!await refresh(ticket)){out.cancelled=true;return out;}
   let batch=[],bytes=2;const used=[];
   async function flush(){if(!batch.length)return;const entries=batch;batch=[];bytes=2;if(ticket!==epoch||cancelled){out.cancelled=true;return;}try{const result=await submit(entries.map(e=>e.operation),{reason});if(ticket!==epoch){out.cancelled=true;return;}accept(result,entries);out.done.push(...entries.map(e=>e.raw));}catch(e){if(ticket!==epoch){out.cancelled=true;return;}out.failed.push(...entries.map(entry=>({row:entry.raw,error:e.message})));}try{onProgress({done:out.done.length,failed:out.failed.length,total:rows.length});}catch(_e){/* UI callbacks cannot change request acceptance. */}notify();}
   for(const raw of rows){if(ticket!==epoch||cancelled){out.cancelled=true;break;}try{const entry=prepare(raw,null);if(used.some(r=>isDuplicate(r,entry.values)))throw Error('업로드 안에 중복 연락처가 있습니다.');const size=new TextEncoder().encode(JSON.stringify(entry.operation,null,1)).length+2;if(size>5*1024*1024-2)throw Error('한 연락처 요청이 5MB를 초과합니다.');if(batch.length>=1000||bytes+size>5*1024*1024)await flush();if(ticket!==epoch||cancelled){out.cancelled=true;break;}batch.push(entry);used.push(entry.values);bytes+=size;}catch(e){out.failed.push({row:raw,error:e.message});}}
   await flush();if(cancelled)out.cancelled=true;return out;
  }catch(e){if(ticket===epoch){state.error=e.message;out.failed=rows.map(row=>({row,error:e.message}));}else out.cancelled=true;return out;}finally{if(ticket===epoch){state.saving=false;notify();}}
 }
 function reset(){epoch++;generation++;local=[];cancelled=true;Object.assign(state,{rows:[],pending:[],loading:false,saving:false,error:'',message:''});notify();}
 return{state,load,save,saveMany,reset,cancel(){cancelled=true;},duplicateRows};
}
function mount({document,sb,client,getCustomers=()=>[],onMessage=()=>{}}){
 let active=false,filter={},dialog=null,editing=null,actor=null,importer=null;
 async function read(){const rows=[];for(let offset=0;;offset+=1000){const {data,error}=await sb.from('contacts').select('*').order('company').order('id').range(offset,offset+999);if(error)throw error;if(!Array.isArray(data))throw Error('연락처 목록이 없습니다.');rows.push(...data);if(data.length<1000)return rows;}}
 async function readPending(){const rows=[],resolvedIds=[];for(let offset=0;;offset+=100){const result=await client.list(100,offset);if(!Array.isArray(result?.requests))throw Error('변경 요청 목록을 확인하지 못했습니다.');for(const req of result.requests){if(req.status!=='pending'){resolvedIds.push(req.id);continue;}for(const op of req.operations||[])if(op.table==='contacts'&&['insert','update'].includes(op.action))rows.push({...op.before,...op.values,id:op.key?.id,_pending:true,_requestId:req.id,_action:op.action});}if(result.requests.length<100)return{rows,resolvedIds};if(offset>=99900)throw Error('대기 요청 조회 범위를 초과했습니다. 관리자에게 문의하세요.');}}
 const controller=createController({read,readPending,submit:(ops,options)=>client.submit(ops,options),onChange:paint});
 function paint(){if(active){const host=document.getElementById('contacts-results');if(host)host.innerHTML=controller.state.loading?'<p role="status">연락처를 불러오는 중입니다…</p>':renderList({rows:controller.state.rows,pending:controller.state.pending,filter});const error=document.getElementById('contacts-error');if(error)error.textContent=controller.state.error;for(const id of ['contacts-new','contacts-upload','contacts-template','contacts-refresh']){const button=document.getElementById(id);if(button)button.disabled=controller.state.saving;}const company=document.getElementById('contacts-company');if(company){const selected=company.value;company.innerHTML='<option value="">업체 전체</option>'+[...new Set(controller.duplicateRows().map(r=>r.company))].sort((a,b)=>a.localeCompare(b,'ko')).map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');company.value=selected;}}
  if(dialog){dialog.querySelector('[data-form-error]').textContent=controller.state.error;dialog.querySelectorAll('input,select,textarea,button').forEach(el=>{el.disabled=controller.state.saving;});}
 }
 function show(){active=true;filter={};document.getElementById('topbar-actions').innerHTML='<button class="btn" id="contacts-template">빈 양식</button><button class="btn" id="contacts-upload">엑셀·CSV 업로드</button><button class="btn btn-primary" id="contacts-new">직접 입력</button>';
  document.getElementById('content').innerHTML='<section class="contacts"><p class="contacts-help">업체별 담당자와 연락처를 관리합니다. 등록·수정 요청은 관리자 승인 후 반영됩니다.</p><div class="contacts-filters"><input id="contacts-q" aria-label="연락처 검색" placeholder="업체 / 담당자 / 이메일 / 전화 검색"><select id="contacts-company" aria-label="업체 필터"><option value="">업체 전체</option></select><select id="contacts-status" aria-label="연락처 상태 필터"><option value="">상태 전체</option>'+statuses.map(s=>`<option>${s}</option>`).join('')+'</select><button class="btn" id="contacts-refresh">새로고침</button></div><p class="contacts-error" id="contacts-error" role="alert"></p><div id="contacts-results"></div></section>';
  document.getElementById('contacts-new').onclick=()=>open();document.getElementById('contacts-upload').onclick=()=>importer?.open();document.getElementById('contacts-template').onclick=()=>importer?.downloadTemplate();document.getElementById('contacts-refresh').onclick=()=>controller.load();
  const update=()=>{filter={q:document.getElementById('contacts-q').value,company:document.getElementById('contacts-company').value,status:document.getElementById('contacts-status').value};paint();};document.getElementById('contacts-q').oninput=update;for(const f of ['company','status'])document.getElementById('contacts-'+f).onchange=update;
  document.getElementById('contacts-results').onclick=e=>{const button=e.target.closest('[data-contact-edit]');if(button)open(button.dataset.contactEdit);};paint();controller.load();
 }
 function close(force=false){if(controller.state.saving&&!force)return false;if(dialog){dialog.close();dialog.remove();dialog=null;}editing=null;return true;}
 function open(id){if(controller.state.saving)return;if(!close())return;const row=id?controller.state.rows.find(r=>r.id===id):null;if(id&&!row)return;editing=row?JSON.parse(JSON.stringify(row)):null;controller.state.error='';dialog=document.createElement('dialog');dialog.className='contacts-dialog';dialog.setAttribute('aria-label',row?'연락처 수정':'연락처 직접 입력');
  const field=([name,label])=>{const attr=`name="${name}" id="contact-${name}"`;let input;if(name==='customer_id')input=`<select ${attr}><option value="">연결 안 함 · 미등록 업체 가능</option>${getCustomers().map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select>`;else if(name==='status')input=`<select ${attr}>${statuses.map(s=>`<option>${s}</option>`).join('')}</select>`;else if(['note','address'].includes(name))input=`<textarea ${attr} rows="2" maxlength="4000"></textarea>`;else input=`<input ${attr} type="${name==='email'?'email':'text'}" maxlength="${name==='email'?254:4000}"${['company','person'].includes(name)?' required':''}>`;return`<label class="contact-field">${esc(label)}${['company','person'].includes(name)?' *':''}${input}</label>`;};
  dialog.innerHTML=`<form><header><h2>${row?'연락처 수정':'연락처 직접 입력'}</h2><button type="button" class="btn" data-close>닫기</button></header><p class="contacts-help">업체·담당자와 연락수단(휴대전화·전화·이메일·메신저) 한 가지는 필수입니다.</p><div class="contact-form-grid">${[fields[17],...fields.slice(0,17)].map(field).join('')}<label class="contact-field contact-full">등록·수정 사유 *<textarea name="reason" required maxlength="2000" rows="2" placeholder="예: 거래처 신규 담당자 연락처 등록"></textarea></label></div><p role="alert" class="contacts-error" data-form-error></p><footer><span>관리자 승인 후 연락처에 반영됩니다.</span><button type="submit" class="btn btn-primary">승인 요청</button></footer></form>`;
  const form=dialog.querySelector('form');for(const [name]of fields)form.elements.namedItem(name).value=row?.[name]??(name==='status'?'활성':'');form.elements.namedItem('customer_id').onchange=()=>{const c=getCustomers().find(c=>c.id===form.elements.namedItem('customer_id').value);if(c){form.elements.namedItem('company').value=c.name||'';form.elements.namedItem('country').value=c.country||'';}};
  dialog.querySelector('[data-close]').onclick=()=>close();dialog.addEventListener('cancel',e=>{e.preventDefault();close();});for(const type of ['keydown','paste'])dialog.addEventListener(type,e=>e.stopPropagation());
  form.onsubmit=async e=>{e.preventDefault();const current=dialog,raw={};for(const [name]of fields)raw[name]=form.elements.namedItem(name).value;const result=await controller.save(raw,editing,form.elements.namedItem('reason').value);if(result&&dialog===current){onMessage(controller.state.message);close();}};document.body.appendChild(dialog);dialog.showModal();form.elements.namedItem('company').focus();
 }
 sb.auth?.onAuthStateChange?.((_event,session)=>{const next=session?.user?.id||null;if(next!==actor){actor=next;close(true);importer?.reset?.();filter={};controller.reset();if(active)show();}});
 return{show,hide(){active=false;close();importer?.close?.();},open,controller,rows:()=>controller.duplicateRows(),reload:()=>controller.load(),setImporter(value){importer=value;}};
}
return{fields,statuses,normalize,isDuplicate,filterRows,renderList,createController,mount,esc};
});

