const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {PGlite}=require('@electric-sql/pglite');
const A='00000000-0000-0000-0000-000000000001',U='00000000-0000-0000-0000-000000000002',O='00000000-0000-0000-0000-000000000003';
test('requests isolate data, self approval is explicit, validation and permissions cannot be bypassed',async()=>{
 const sql=fs.readFileSync(require('node:path').join(__dirname,'../sql/change-approvals.sql'),'utf8');
 const db=new PGlite();
 try{
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb default '{}',raw_user_meta_data jsonb default '{}');
 insert into auth.users values('${A}','entropyadmin@entropy.internal',now(),'{}','{}'),('${U}','member@entropymakeup.com',now(),'{}','{}'),('${O}','outside@example.com',now(),'{}','{"dashboard_admin":true}');
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table public.customers(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz default now());
 create table public.products(id uuid primary key default gen_random_uuid(),name text not null,price numeric,created_at timestamptz default now());
 create table public.invoices(id uuid primary key default gen_random_uuid(),no text unique not null,customer text,note text,created_at timestamptz default now());
 create table public.invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices on delete cascade,name text,qty numeric,price numeric,sales_type text,created_at timestamptz default now());
 create table public.invoice_drive_documents(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices on delete cascade,name text);
 create table public.documents(id uuid primary key default gen_random_uuid(),name text);
 create table public.stocks(id uuid primary key default gen_random_uuid(),name text,qty numeric);
 create table public.schedules(id uuid primary key default gen_random_uuid(),title text,date date);
 create table public.tax_records(id uuid primary key default gen_random_uuid(),customer_id uuid,month text,status text,unique(customer_id,month));
 create table public.app_settings(key text primary key,value text);
 create table public.product_details(barcode text primary key,name_kr text);
 create table public.tax_invoice_amounts(approval_number text primary key,gross_amount numeric);
 create table public.test_outbox(id uuid);
 create schema storage;create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;grant select,insert,update,delete on storage.objects to authenticated;
 create policy existing_storage_access on storage.objects for all to authenticated using(true) with check(true);
 insert into storage.objects(bucket_id,name) values('documents','confirmed.pdf'),('invoice-docs','old/file.pdf');
 create function public.test_capture() returns trigger language plpgsql as $$begin insert into public.test_outbox values(new.id);return new;end$$;
 create trigger capture after insert or update on public.products for each row execute function public.test_capture();
 grant usage on schema public,auth to authenticated,anon;
 grant select,insert,update,delete on all tables in schema public to authenticated;
 create function public.save_invoice_atomic(p_id text,p_invoice jsonb,p_items jsonb) returns jsonb language plpgsql as $$declare v_id uuid;begin
 if p_id is null then insert into public.invoices(no,customer,note) values(p_invoice->>'no',p_invoice->>'customer',p_invoice->>'note') returning id into v_id;
 else v_id:=p_id::uuid;update public.invoices set no=p_invoice->>'no',customer=p_invoice->>'customer',note=p_invoice->>'note' where id=v_id;delete from public.invoice_items where invoice_id=v_id;end if;
 insert into public.invoice_items(invoice_id,name,qty,price,sales_type) select v_id,x->>'name',(x->>'qty')::numeric,(x->>'price')::numeric,x->>'sales_type' from jsonb_array_elements(p_items) x;
 return jsonb_build_object('id',v_id);end$$;
 insert into products(id,name,price) values('10000000-0000-0000-0000-000000000001','Original',100);truncate test_outbox;
 `);
 await db.exec(sql);
 const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 const get=async(table)=> (await db.query(`select to_jsonb(t) r from public.${table} t order by 1::text`)).rows.map(x=>x.r);
 const submit=async(ops,client=crypto.randomUUID(),reason='검토 요청')=>(await db.query('select public.submit_change_request($1::jsonb,$2,$3::uuid) r',[JSON.stringify(ops),reason,client])).rows[0].r;
 const review=async(id,approve=true,note='')=>(await db.query('select public.review_change_request($1::uuid,$2,$3) r',[id,approve,note])).rows[0].r;
 const list=async()=>(await db.query('select public.list_change_requests() r')).rows[0].r;
 await db.exec('set role anon');await assert.rejects(list,/permission denied/);
 await login(O);await assert.rejects(list,/UNAUTHORIZED/);
 await login(A);const before=(await get('products'))[0];const op={table:'products',action:'update',key:{id:before.id},before,values:{price:200}};
 await assert.rejects(()=>db.query('update products set price=300'),/APPROVAL_REQUIRED/);
 await db.query("select set_config('app.approval','true',false)");
 await assert.rejects(()=>db.query('update products set price=300'),/APPROVAL_REQUIRED/);
 const client=crypto.randomUUID();const pending=await submit([op],client);assert.equal(pending.status,'pending');
 assert.equal((await get('products'))[0].price,100);assert.equal((await get('test_outbox')).length,0,'dry-run side effects rolled back');
 assert.equal((await submit([op],client)).id,pending.id);
 await assert.rejects(()=>submit([{...op,values:{price:201}}],client),/CLIENT_ID_REUSED/);
 assert.equal((await list()).is_admin,true);
 await login(U);await assert.rejects(()=>review(pending.id),/ADMIN_REQUIRED/);assert.equal((await list()).requests.length,0);
 await login(A);assert.equal((await review(pending.id)).status,'approved');assert.equal((await get('products'))[0].price,200);assert.equal((await get('test_outbox')).length,1);
 await assert.rejects(()=>review(pending.id),/ALREADY_REVIEWED/);
 await assert.rejects(()=>submit([op]),/STALE_DATA/);
 const fresh=(await get('products'))[0];const newop={...op,before:fresh,values:{price:300}};
 const p1=await submit([newop]),p2=await submit([{...newop,values:{price:400}}]);await review(p1.id);await assert.rejects(()=>review(p2.id),/STALE_DATA/);
 assert.equal((await list()).requests.find(x=>x.id===p2.id).status,'pending');assert.equal((await get('products'))[0].price,300);
 await assert.rejects(()=>review(p2.id,false,''),/REJECTION_REASON_REQUIRED/);await review(p2.id,false,'원본 재확인');assert.equal((await get('products'))[0].price,300);
 for(const bad of [[],[{table:'users',action:'insert',values:{}}],[{table:'tax_invoice_amounts',action:'insert',values:{approval_number:'x'}}],[{table:'products',action:'insert',before:null,values:{name:'',price:2}}],[{table:'products',action:'insert',before:null,values:{name:'Bad',price:'NaN'}}],[{table:'products',action:'insert',before:null,values:{name:'Bad',unknown:3}}]]) await assert.rejects(()=>submit(bad));
 const rows=await get('products');await assert.rejects(()=>submit([{table:'products',action:'insert',before:null,values:{name:'Rollback',price:1}},{table:'products',action:'insert',before:null,values:{price:1}}]));assert.deepEqual(await get('products'),rows);
 await login(U);const own=await submit([{table:'customers',action:'insert',before:null,values:{name:'New'}}]);assert.equal((await get('customers')).length,0);assert.equal((await list()).requests.length,1);
 await login(A);await review(own.id);assert.equal((await get('customers')).length,1);
 // Unknown function/column injection and immutable primary keys are rejected.
 await assert.rejects(()=>submit([{table:'products;drop table customers',action:'delete',key:{id:before.id},before}]));
 await assert.rejects(()=>submit([{...newop,before:(rows[0]),values:{id:crypto.randomUUID()}}]));
 const invoice={action:'invoice',id:null,before:null,invoice:{no:'TEST-1',customer:'New',note:'test'},items:[{name:'Product',qty:2,price:10,sales_type:'Paid'}]};
 const ip=await submit([invoice]);assert.equal((await get('invoices')).length,0);await review(ip.id);assert.equal((await get('invoices')).length,1);assert.equal((await get('invoice_items')).length,1);
 await assert.rejects(()=>submit([{...invoice,invoice:{no:'TEST-2',customer:'New'},items:[{name:'Bad',qty:null,price:10,sales_type:'Paid'}]}]),/INVALID/);
 await assert.rejects(()=>db.query("select public.save_invoice_atomic(null,'{\"no\":\"BYPASS\"}','[]')"),/APPROVAL_REQUIRED/);
 const inv=(await get('invoices'))[0],its=await get('invoice_items');
 const del={table:'invoices',action:'delete',key:{id:inv.id},before:inv,before_items:its,before_drive_documents:[]};
 await assert.rejects(()=>submit([{...del,before_items:[]}]),/STALE_DATA/);
 const dp=await submit([del]);assert.equal((await get('invoice_items')).length,1);
 await db.exec(`reset role;create function public.reject_approval_delete() returns trigger language plpgsql as $$begin raise exception 'fixture trigger failure';end$$;create trigger reject_delete before delete on public.invoices for each row execute function public.reject_approval_delete();set role authenticated;`);
 await assert.rejects(()=>review(dp.id),/fixture trigger failure/);assert.equal((await get('invoices')).length,1);assert.equal((await get('invoice_items')).length,1);
 assert.equal((await list()).requests.find(r=>r.id===dp.id).status,'pending');
 await db.exec('reset role;drop trigger reject_delete on public.invoices;set role authenticated');await review(dp.id);
 assert.equal((await get('invoices')).length,0);assert.equal((await get('invoice_items')).length,0);
 await assert.rejects(()=>db.query('select * from approval_private.requests'),/permission denied/);
 await assert.rejects(()=>db.query('select approval_private.apply_operations($1::jsonb)',[JSON.stringify([op])]),/permission denied/);
 await assert.rejects(()=>db.query('insert into approval_private.apply_context values(txid_current(),$1::uuid)',[A]),/permission denied/);
 for(const [table,values] of [['documents',{type:'기타'}],['stocks',{qty:1}],['invoice_items',{name:'missing amounts'}]]) await assert.rejects(()=>submit([{table,action:'insert',before:null,values}]),/INVALID/);
 await assert.rejects(()=>submit([{table:'invoices',action:'insert',before:null,values:{no:'MISSING-CUSTOMER'}}]),/INVALID/);
 await assert.rejects(()=>db.exec('truncate public.products'),/permission denied/);
 await db.exec('reset role;grant truncate on public.products to authenticated;set role authenticated');
 await assert.rejects(()=>db.exec('truncate public.products'),/APPROVAL_REQUIRED/);
 assert.equal((await db.query("select * from storage.objects where name='confirmed.pdf'")).rows.length,1);
 assert.equal((await db.query("update storage.objects set name='changed.pdf' where name='confirmed.pdf' returning *")).rows.length,0);
 assert.equal((await db.query("delete from storage.objects where name='confirmed.pdf' returning *")).rows.length,0);
 await assert.rejects(()=>db.query("insert into storage.objects(bucket_id,name) values('invoice-docs','new/file.pdf')"),/row-level security/);
 await assert.rejects(()=>db.query("insert into storage.objects(bucket_id,name) values('documents','confirmed2.pdf')"),/row-level security/);
 await db.query("insert into storage.objects(bucket_id,name) values('documents','pending/00000000-0000-0000-0000-000000000001/new.pdf')");
 }finally{await db.close();}
});
