const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
function setup(response={data:{id:'r1',status:'pending'}},reason='변경 사유'){const ctx={crypto:require('node:crypto').webcrypto,TextEncoder};vm.createContext(ctx);vm.runInContext(fs.readFileSync('change-requests.js','utf8'),ctx);const calls=[];const client=ctx.ChangeRequests.createClient({sb:{rpc:async(n,a)=>{calls.push({n,a});if(response instanceof Error)throw response;return response;},from(){throw Error('unexpected DB read');}},promptReason:()=>reason});return{client,calls};}
test('submit queues full before snapshot without changing it',async()=>{const h=setup();const before={id:'a',name:'old',other:null};const op=await h.client.row('products','update',{id:'a'},{name:'new'},before);const result=await h.client.submit([op]);assert.equal(result.status,'pending');assert.equal(before.name,'old');assert.equal(h.calls[0].n,'submit_change_request');assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0].a.p_operations[0].before)),before);});
test('cancel and blank reason never submit',async()=>{for(const r of [null,' ']){const h=setup(undefined,r);assert.equal(await h.client.submit([{action:'insert'}]),null);assert.equal(h.calls.length,0);}});
test('ambiguous error retry retains client id; duplicate clicks share submission',async()=>{const h=setup(new Error('network'));const ops=[{action:'insert',table:'products',values:{name:'A'},before:null,key:{}}];await assert.rejects(h.client.submit(ops));await assert.rejects(h.client.submit(ops));assert.equal(h.calls[0].a.p_client_id,h.calls[1].a.p_client_id);});
test('malformed result fails closed',async()=>{const h=setup({data:{id:'r1',status:'invalid'}});await assert.rejects(h.client.submit([{action:'insert'}]),/확인/);});
test('invoice snapshots preserve full rows and sort children',async()=>{const h=setup();const op=await h.client.invoice('i',{no:'changed'},[],{invoice:{id:'i',no:'old'},items:[{id:'z'},{id:'a'}]});assert.equal(op.before.items[0].id,'a');assert.equal(op.before.invoice.no,'old');});
test('concurrent reason prompts coalesce into one request and acknowledged new intent gets new ID',async()=>{const h=setup();const ops=[{action:'insert',values:{name:'X'}}];await Promise.all([h.client.submit(ops),h.client.submit(ops)]);assert.equal(h.calls.length,1);await h.client.submit(ops);assert.equal(h.calls.length,2);assert.notEqual(h.calls[0].a.p_client_id,h.calls[1].a.p_client_id);});

test('terminal retry response is returned honestly',async()=>{const h=setup({data:{id:'r',status:'approved'}});assert.equal((await h.client.submit([{action:'insert'}])).status,'approved');});
test('updates omit unchanged primary key and reject attempted key changes',async()=>{const h=setup();const op=await h.client.row('product_details','update',{barcode:'123'},{barcode:'123',name:'New'},{barcode:'123',name:'Old'});assert.equal('barcode' in op.values,false);await assert.rejects(h.client.row('product_details','update',{barcode:'123'},{barcode:'456'},{barcode:'123'}),/키/);});
test('asynchronous reason dialog is shared by concurrent submissions',async()=>{const ctx={crypto:require('node:crypto').webcrypto,TextEncoder};vm.createContext(ctx);vm.runInContext(fs.readFileSync('change-requests.js','utf8'),ctx);let finish,prompts=0,calls=0;const client=ctx.ChangeRequests.createClient({sb:{rpc:async()=>{calls++;return{data:{id:'r',status:'pending'}};}},promptReason:()=>{prompts++;return new Promise(r=>finish=r);}});const ops=[{action:'insert'}];const a=client.submit(ops),b=client.submit(ops);await new Promise(setImmediate);assert.equal(prompts,1);finish('사유');await Promise.all([a,b]);assert.equal(calls,1);});
test('account changes discard retry identities and suppress old-account acknowledgement',async()=>{const ctx={crypto:require('node:crypto').webcrypto,TextEncoder};vm.createContext(ctx);vm.runInContext(fs.readFileSync('change-requests.js','utf8'),ctx);let auth,done;const ids=[];const client=ctx.ChangeRequests.createClient({sb:{auth:{onAuthStateChange:fn=>{auth=fn;}},rpc:async(n,a)=>{ids.push(a.p_client_id);return new Promise(r=>done=r);}},promptReason:()=> '사유'});const ops=[{action:'insert'}];auth('SIGNED_IN',{user:{id:'a'}});const first=client.submit(ops);await new Promise(setImmediate);auth('SIGNED_IN',{user:{id:'b'}});done({data:{id:'r',status:'pending'}});await assert.rejects(first,/계정/);const next=client.submit(ops);await new Promise(setImmediate);assert.notEqual(ids[0],ids[1]);done({data:{id:'next',status:'pending'}});await next;});
