const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {randomUUID}=require('node:crypto');
const {createDatabase,ADMIN,MEMBER}=require('./helpers/invoice-amount-db.cjs');
const migration=path.join(__dirname,'../sql/invoice-number-allocation.sql');
const op=(no='BL_20260910_2',qty=100)=>({action:'invoice',auto_number:true,id:null,before:null,invoice:{no,customer:'Synthetic customer',order_date:'2026-09-10',status:'Ordered',foc:false},items:[{name:'Synthetic item',barcode:'TEST',qty,price:5760,sales_type:'Paid'}]});

test('automatic numbers reserve pending requests, survive retries and approve in either order',async()=>{
 const db=await createDatabase();
 try{
  await db.exec("alter table public.customers add column code text; alter table public.customers disable trigger user; insert into public.customers(name,code) values('Synthetic customer','BL'); alter table public.customers enable trigger user;");
  if(fs.existsSync(migration))await db.exec(fs.readFileSync(migration,'utf8'));
  const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
  const submit=async(ops,client=randomUUID())=>(await db.query('select public.submit_change_request($1::jsonb,$2,$3::uuid) r',[JSON.stringify(ops),'Synthetic request',client])).rows[0].r;
  const list=async()=>(await db.query('select public.list_change_requests() r')).rows[0].r.requests;
  const review=async(id,approve=true)=>(await db.query('select public.review_change_request($1::uuid,$2,$3) r',[id,approve,approve?'':'Synthetic rejection'])).rows[0].r;
  await login(MEMBER);
  const first=await submit([op()]);
  const client=randomUUID(),second=await submit([op(undefined,640)],client);
  let requests=await list();
  assert.equal(requests.find(r=>r.id===first.id).operations[0].invoice.no,'BL_20260910_2');
  assert.equal(requests.find(r=>r.id===second.id).operations[0].invoice.no,'BL_20260910_3','second pending request must reserve a different number');
  assert.deepEqual(await submit([op(undefined,640)],client),second,'retry must return same reservation');
  await assert.rejects(()=>submit([op(undefined,641)],client),/CLIENT_ID_REUSED/);
  await assert.rejects(()=>review(first.id),/ADMIN_REQUIRED/);
  await assert.rejects(()=>db.query('select approval_private.allocate_invoice_numbers($1::jsonb)',[JSON.stringify([op()])]),/permission denied/);
  assert.equal((await db.query("select count(*)::int n from public.invoices where no like 'BL_%'")).rows[0].n,0,'submit must not persist invoices');
  await login(ADMIN);
  await review(second.id);await review(first.id);
  assert.deepEqual((await db.query("select no from public.invoices where no like 'BL_%' order by no")).rows.map(r=>r.no),['BL_20260910_2','BL_20260910_3']);
  await login(MEMBER);assert.deepEqual(await submit([op(undefined,640)],client),{...second,status:'approved'});
  const batch=await submit([op(),op(undefined,20)]);
  requests=await list();assert.deepEqual(requests.find(r=>r.id===batch.id).operations.map(o=>o.invoice.no),['BL_20260910_4','BL_20260910_5']);
  await login(ADMIN);await review(batch.id,false);
  const reused=await submit([op()]);assert.equal((await list()).find(r=>r.id===reused.id).operations[0].invoice.no,'BL_20260910_4');
  const before=(await list()).length;
  await assert.rejects(()=>submit([op(),{table:'products',action:'insert',before:null,values:{name:''}}]),/INVALID/);
  assert.equal((await list()).length,before,'invalid batch leaves no reservations');
  const next=await submit([op()]);assert.equal((await list()).find(r=>r.id===next.id).operations[0].invoice.no,'BL_20260910_5');
  const custom=await submit([op('CUSTOM-123')]);await review(custom.id);
  await assert.rejects(()=>submit([op('CUSTOM-123')]),/INVOICE_NUMBER_CONFLICT/);
  const badCustomer=op('BL_20260910_2');badCustomer.invoice.customer='Other';await assert.rejects(()=>submit([badCustomer]),/INVOICE_NUMBER_CONFLICT/);
  const invoice=(await db.query("select to_jsonb(i) r from public.invoices i where no='BL_20260910_2'")).rows[0].r;
  const items=(await db.query('select to_jsonb(i) r from public.invoice_items i where invoice_id=$1 order by id',[invoice.id])).rows.map(r=>r.r);
  const edit={...op(),id:invoice.id,before:{invoice,items}};
  await assert.rejects(()=>submit([{...edit,invoice:{...edit.invoice,no:'BL_20260910_4'}}]),/INVOICE_NUMBER_CONFLICT/,'editing must not steal a pending reservation');
  await assert.rejects(()=>submit([{table:'invoices',action:'update',key:{id:invoice.id},before:invoice,values:{no:'BL_20260910_4'}}]),/INVOICE_NUMBER_CONFLICT/);
  await assert.rejects(()=>submit([{table:'invoices',action:'insert',before:null,values:{no:'BL_20260910_4',customer:'Synthetic customer'}}]),/INVOICE_NUMBER_CONFLICT/);
  const explicit=op();delete explicit.auto_number;
  await assert.rejects(()=>submit([explicit]),/INVOICE_NUMBER_CONFLICT/,'explicit standard-shaped references must not be renamed');
  const editing=await submit([edit]);assert.equal((await list()).find(r=>r.id===editing.id).operations[0].invoice.no,invoice.no);
  await review(editing.id);
  const fixed=op('BL_20260910_6');delete fixed.auto_number;
  const mixed=await submit([op('BL_20260910_6'),fixed]);
  assert.deepEqual((await list()).find(r=>r.id===mixed.id).operations.map(o=>o.invoice.no),['BL_20260910_7','BL_20260910_6']);
 }finally{await db.close();}
});
