const {test}=require('node:test'),assert=require('node:assert/strict');const {harness}=require('./helpers/approvals.cjs');
function setup(options){const h=harness(options);h.load('confirmRawUpload','renderRawUploadStatus','discardRawUpload','openRawUploadModal');h.ctx._showRawPreviewModal=()=>{};h.ctx.window._rawUploadData=[{customer:'A',orderDate:'2026-09-11',items:[{name:'N',barcode:'123',qty:1,price:3,salesType:'Paid'}]},{customer:'B',orderDate:'2026-09-11',items:[{name:'P',barcode:'456',qty:2,price:4,salesType:'FOC'}]}];return h;}
test('Excel submits one atomic request containing all complete orders without confirmed cache changes',async()=>{const h=setup();await h.ctx.confirmRawUpload();assert.equal(h.calls.length,1);const ops=h.calls[0].args.p_operations;assert.equal(ops.length,2);assert.equal(ops[0].before,null);assert.equal(ops[1].items[0].sales_type,'FOC');assert.notEqual(ops[0].invoice.no,ops[1].invoice.no);assert.equal(h.ctx._invoices.length,1);assert.ok(h.ctx.window._rawUploadData.every(g=>g._saveStatus==='requested'));assert.match(h.element('raw-upload-status').innerHTML,/승인 대기/);await h.ctx.confirmRawUpload();assert.equal(h.calls.length,1);});
test('batch failure preserves all rows, reserved numbers and same retry client ID',async()=>{let count=0;const h=setup({execute:async()=>++count===1?{error:{code:'23514',message:'invalid'}}:{data:{id:'r',status:'pending'}}});await h.ctx.confirmRawUpload();assert.ok(h.ctx.window._rawUploadData.every(g=>g._saveStatus==='failed'));const no=h.ctx.window._rawUploadData[0]._saveInvoice.no;h.ctx._invoices.push({id:'other',no});await h.ctx.confirmRawUpload();assert.equal(h.calls[0].args.p_client_id,h.calls[1].args.p_client_id);assert.equal(h.calls[1].args.p_operations[0].invoice.no,no);assert.ok(h.ctx.window._rawUploadData.every(g=>g._saveStatus==='requested'));});
test('lost response and malformed acknowledgement mark all rows unconfirmed, never submitted success',async()=>{for(const options of [{execute:async()=>{throw Error('offline')}},{response:{data:{invoice:{id:'unexpected'}}}}]){const h=setup(options);await h.ctx.confirmRawUpload();assert.ok(h.ctx.window._rawUploadData.every(g=>g._saveStatus==='unknown'));assert.equal(h.ctx._items.length,1);assert.equal(h.closed.length,0);}});
test('cancelled reason retains batch as unprocessed and sends no RPC',async()=>{const h=setup({reason:null});await h.ctx.confirmRawUpload();assert.equal(h.calls.length,0);assert.ok(h.ctx.window._rawUploadData.every(g=>g._saveStatus==='pending'));});
test('duplicate clicks and discard while batch pending cannot replace batch',async()=>{let done;const h=setup({execute:()=>new Promise(r=>done=r)}),batch=h.ctx.window._rawUploadData;const a=h.ctx.confirmRawUpload(),b=h.ctx.confirmRawUpload();await new Promise(setImmediate);h.ctx.discardRawUpload();assert.equal(h.ctx.window._rawUploadData,batch);assert.equal(h.calls.length,1);done({data:{id:'r',status:'pending'}});await Promise.all([a,b]);});
test('missing customers and empty orders fail before submission',async()=>{const h=setup();h.ctx.window._rawUploadData[0].items=[];await h.ctx.confirmRawUpload();assert.equal(h.calls.length,0);});
test('explicit discard clears only draft results and never confirmed orders',async()=>{const h=setup();h.ctx.discardRawUpload();assert.equal(h.ctx.window._rawUploadData,null);assert.equal(h.ctx._invoices.length,1);});
