const {test}=require('node:test');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const A='00000000-0000-0000-0000-000000000001',U='00000000-0000-0000-0000-000000000002',O='00000000-0000-0000-0000-000000000003';
test('owner revises pending request atomically; stale reviewers and other users cannot change it',async()=>{
const db=new PGlite();try{
 await db.exec(`create role anon; create role authenticated; create schema auth;
 create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_app_meta_data jsonb default '{}',raw_user_meta_data jsonb default '{}');
 insert into auth.users values('${A}','entropyadmin@entropy.internal',now(),'{}','{}'),('${U}','member@entropymakeup.com',now(),'{}','{}'),('${O}','outside@example.com',now(),'{}','{"dashboard_admin":true}');
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create table public.customers(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz default now());
 create table public.products(id uuid primary key default gen_random_uuid(),name text not null,price numeric,created_at timestamptz default now());
 create table public.invoices(id uuid primary key default gen_random_uuid(),no text unique not null,customer text,note text,created_at timestamptz default now());
 create table public.invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices on delete cascade,name text,qty numeric,price numeric,sales_type text,created_at timestamptz default now());
 create table public.invoice_drive_documents(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices on delete cascade,name text);
 create table public.documents(id uuid primary key default gen_random_uuid(),name text);
 create table public.stocks(id uuid primary key default gen_random_uuid(),name text,qty numeric);
 create table public.schedules(id uuid primary key default gen_random_uuid(),title text,date date);
 create table public.tax_records(id uuid primary key default gen_random_uuid(),customer_id uuid,month text,status text,unique(customer_id,month));
 create table public.app_settings(key text primary key,value text);
 create table public.product_details(barcode text primary key,name_kr text);
 create table public.tax_invoice_amounts(approval_number text primary key,gross_amount numeric);
 create table public.test_outbox(id uuid);
 create schema storage;create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,unique(bucket_id,name));
 alter table storage.objects enable row level security;
 grant usage on schema storage to authenticated;grant select,insert,update,delete on storage.objects to authenticated;
 create policy existing_storage_access on storage.objects for all to authenticated using(true) with check(true);
 insert into storage.objects(bucket_id,name) values('documents','confirmed.pdf'),('invoice-docs','old/file.pdf');
 create function public.test_capture() returns trigger language plpgsql as $$begin insert into public.test_outbox values(new.id);return new;end$$;
 create trigger capture after insert or update on public.products for each row execute function public.test_capture();
 grant usage on schema public,auth to authenticated,anon;
 grant select,insert,update,delete on all tables in schema public to authenticated;
 create function public.save_invoice_atomic(p_id text,p_invoice jsonb,p_items jsonb) returns jsonb language plpgsql as $$declare v_id uuid;begin
 if p_id is null then insert into public.invoices(no,customer,note) values(p_invoice->>'no',p_invoice->>'customer',p_invoice->>'note') returning id into v_id;
 else v_id:=p_id::uuid;update public.invoices set no=p_invoice->>'no',customer=p_invoice->>'customer',note=p_invoice->>'note' where id=v_id;delete from public.invoice_items where invoice_id=v_id;end if;
 insert into public.invoice_items(invoice_id,name,qty,price,sales_type) select v_id,x->>'name',(x->>'qty')::numeric,(x->>'price')::numeric,x->>'sales_type' from jsonb_array_elements(p_items) x;
 return jsonb_build_object('id',v_id);end$$;
 insert into products(id,name,price) values('10000000-0000-0000-0000-000000000001','Original',100);truncate test_outbox;
 `);

await db.exec(fs.readFileSync(path.join(__dirname,'../sql/change-approvals.sql'),'utf8'));
await db.exec('alter table invoices add column status text, add column ship_status text, add column pay_date date, add column ship_date date; alter table customers add column code text;');
await db.exec(fs.readFileSync(path.join(__dirname,'../sql/invoice-number-allocation.sql'),'utf8'));
const migration=path.join(__dirname,'../sql/request-revisions.sql');if(fs.existsSync(migration))await db.exec(fs.readFileSync(migration,'utf8'));
const login=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
const list=async()=>(await db.query('select public.list_change_requests() r')).rows[0].r;
const submit=async ops=>(await db.query('select public.submit_change_request($1::jsonb,$2,$3::uuid) r',[JSON.stringify(ops),'최초 요청',crypto.randomUUID()])).rows[0].r;
const revise=async(id,version,ops,reason='보완 요청')=>(await db.query('select public.revise_change_request($1::uuid,$2::integer,$3::jsonb,$4) r',[id,version,JSON.stringify(ops),reason])).rows[0].r;
const review=async(id,version)=>(await db.query('select public.review_change_request_versioned($1::uuid,true,\'\',$2::integer) r',[id,version])).rows[0].r;
await login(U);const before=(await db.query('select to_jsonb(p) r from products p')).rows[0].r;
const op={table:'products',action:'update',key:{id:before.id},before,values:{price:200}};
const r=await submit([op]);const changed={...op,values:{price:350}};
const edited=await revise(r.id,1,[changed]);assert.equal(edited.revision,2);
assert.equal((await db.query('select price from products')).rows[0].price,'100');
assert.equal((await db.query('select * from test_outbox')).rows.length,0);
const own=(await list()).requests.find(x=>x.id===r.id);assert.equal(own.can_edit,true);assert.equal(own.history.length,1);assert.equal(own.history[0].operations[0].values.price,200);
await assert.rejects(()=>revise(r.id,1,[op]),/REQUEST_UPDATED/);
await assert.rejects(()=>revise(r.id,2,[{...changed,key:{id:crypto.randomUUID()}}]),/REQUEST_SCOPE/);
await assert.rejects(()=>revise(r.id,2,[{...changed,values:{unknown_field:1}}]),/INVALID/);
assert.equal((await list()).requests[0].revision,2);
await login(A);await assert.rejects(()=>revise(r.id,2,[op]),/OWNER_REQUIRED/);
await assert.rejects(()=>review(r.id,1),/REQUEST_UPDATED/);
await assert.rejects(()=>db.query('select public.review_change_request($1::uuid,true,\'\')',[r.id]),/REQUEST_UPDATED/);
await review(r.id,2);assert.equal((await db.query('select price from products')).rows[0].price,'350');
await login(U);await assert.rejects(()=>revise(r.id,2,[op]),/ALREADY_REVIEWED/);
await assert.rejects(()=>db.query('select * from approval_private.request_revisions'),/permission denied/);
await login(A);const seed=await submit([{table:'invoices',action:'insert',before:null,values:{no:'TEST',customer:'New',status:'Ordered',ship_status:'준비중'}}]);await review(seed.id,1);
await login(U);const inv=(await db.query('select to_jsonb(i) r from invoices i')).rows[0].r;
const status={table:'invoices',action:'update',key:{id:inv.id},before:inv,values:{status:'Paid',pay_date:'2026-09-29'}};
const sr=await submit([status]);const candidates=(await db.query('select public.find_my_invoice_requests($1::uuid) r',[inv.id])).rows[0].r;assert.equal(candidates.length,1);
await revise(sr.id,1,[{...status,values:{...status.values,ship_status:'출고완료',ship_date:'2026-09-29'}}]);
await login(A);await review(sr.id,2);const result=(await db.query('select status,ship_status from invoices')).rows[0];assert.deepEqual(result,{status:'Paid',ship_status:'출고완료'});
await login(U);const freshInv=(await db.query('select to_jsonb(i) r from invoices i')).rows[0].r;
const partial={table:'invoices',action:'update',key:{id:freshInv.id},before:freshInv,values:{note:'보완'}};
const pr=await submit([partial]);const full={action:'invoice',id:freshInv.id,before:{invoice:freshInv,items:[]},invoice:{no:freshInv.no,customer:freshInv.customer,note:'품목도 보완'},items:[{name:'New item',qty:2,price:10,sales_type:'Paid'}]};
await assert.rejects(()=>revise(pr.id,1,[{...full,id:crypto.randomUUID()}]),/REQUEST_SCOPE/);
await revise(pr.id,1,[full]);assert.equal((await db.query('select * from invoice_items')).rows.length,0);
await login(A);await review(pr.id,2);assert.equal((await db.query('select qty from invoice_items')).rows[0].qty,'2');
await login(O);await assert.rejects(()=>revise(sr.id,2,[status]),/UNAUTHORIZED/);
await db.exec('reset role;set role anon');await assert.rejects(()=>revise(sr.id,2,[status]),/permission denied/);
}finally{await db.close();}});
